name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    
    - name: Build the Docker image base
      run:  docker build . --file Dockerfile.base --tag awoland/dsmpkg-env:7.0-base 

    - name: Docker Push the Image base
      run:  docker push awoland/dsmpkg-env:7.0-base
      
    - name: Build the Docker image platform
      run:  docker build . --file Dockerfile --tag awoland/dsmpkg-env:7.0-monaco 

    - name: Docker Push the Image platform
      run:  docker push awoland/dsmpkg-env:7.0-monaco
